## This file was auto-generated by CloudCoreo CLI
	## This file was automatically generated using the CloudCoreo CLI
	##
	## This config.rb file exists to create and maintain services not related to compute.
	## for example, a VPC might be maintained using:
	##
	## coreo_aws_vpc_vpc "my-vpc" do
	##   action :sustain
	##   cidr "12.0.0.0/16"
	##   internet_gateway true
	## end
	##

coreo_aws_advisor_alert "elb-inventory" do
  action :define
  service :elb
  #include_violations_in_count false
  display_name "ELB Object Health Check"
  description "Load balancer health check is greater then 2 min."
  category "Inventory"
  suggested_action "None."
  level "Informational"
  objectives ["load_balancers"]
  audit_objects ["load_balancer_descriptions.health_check.interval"]
  operators [">"]
  alert_when [1]
end

coreo_aws_advisor_elb "advise-elb" do
  alerts ${AUDIT_AWS_ELB_ALERT_LIST}
  action :advise
  regions ${AUDIT_AWS_ELB_REGIONS}
end